### ISSUE TITLE
building for target webgpu results in "ValueError: At least one GPU backend is expected to be enabled"

### ISSUE THREAD

**Issue by Abdull** [mlc-ai/web-stable-diffusion#28]
Using version https://github.com/mlc-ai/web-stable-diffusion/tree/ce0c2fbd0fffd7ee39e7be9da34052a8809d98db

environment: Ubuntu 22 LTS server without graphics card.

Executing
```
python3 build.py --target webgpu
```

causes the following error:
```
Traceback (most recent call last):
  File "build.py", line 153, in <module>
    torch_dev_key = utils.detect_available_torch_device()
  File "web_stable_diffusion/utils.py", line 14, in detect_available_torch_device
    raise ValueError("At least one GPU backend is expected to be enabled")
ValueError: At least one GPU backend is expected to be enabled
```

**Comment by ford442** [comment]
I am using that step by changing build.py:153 to simply say "cuda" - the only other option being 'Metal' for MacOS.
Perhaps you are mixing using the commands to assign tvm target etc in the colab cells - then on the Terminal CLI - there is no torch-dev-key variable defined.

**Comment by TigerVersusT** [comment]
you should choose gpu supported wheel at that page, the default link links to a cpu version of wheel
